name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
            file_ext: .exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            code-target: darwin-x64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: dtolnay/rust-toolchain@nightly

      - name: Test
        run: cargo test -- --show-output

      - run: cargo build --release

      - run: |
          mkdir ./dist ./out
          mv ../target/release/nvse-lsp${{ matrix.file_ext }} ./dist/nvse-lsp${{ matrix.file_ext }}
          npm i
          npx vsce pack -o ./out/vscode-nvse-lsp-${{ matrix.target }}.vsix
        working-directory: ./vscode
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: nvse-lsp-${{ matrix.target }}
          path: ./vscode/dist/nvse-lsp${{ matrix.file_ext }}
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-nvse-lsp-${{ matrix.target }}
          path: ./vscode/out

  publish-nightly:
    name: publish
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - run: echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - run: 'echo "HEAD_SHA: $HEAD_SHA"'

      - uses: actions/download-artifact@v7
        with:
          name: nvse-lsp-x86_64-pc-windows-msvc
          path: dist
      - run: |
          tar -czf ./dist/nvse-lsp-windows.tgz ./dist/nvse-lsp.exe
          rm ./dist/nvse-lsp.exe

      - uses: actions/download-artifact@v7
        with:
          name: nvse-lsp-x86_64-unknown-linux-gnu
          path: dist
      - run: |
          tar -czf ./dist/nvse-lsp-linux.tgz ./dist/nvse-lsp
          rm ./dist/nvse-lsp

      - uses: actions/download-artifact@v7
        with:
          name: nvse-lsp-x86_64-apple-darwin
          path: dist
      - run: |
          tar -czf ./dist/nvse-lsp-macos.tgz ./dist/nvse-lsp
          rm ./dist/nvse-lsp

      - uses: actions/download-artifact@v7
        with:
          pattern: vscode-*
          path: ./dist
          merge-multiple: true

      - run: ls -la ./dist

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: "dist/*"
